@startuml
'https://plantuml.com/class-diagram

interface Device<<interface>> {
+ turnOn()
+ turnOff()
}

class DeviceGroup {
+ turnOn()
+ turnOff()
+ addDevice(d : Device)
+ removeDevice(d : Device)
}

Device <|.. Aircon
Device <|.. Light
Device <|.. Elevator

DeviceGroup o.. Device
DeviceGroup ..> Device

@enduml