@startuml
'https://plantuml.com/class-diagram

class ListUI {
}
interface Image<<interface>> {
+ draw()
}
class ProxyImage {
- real : RealImage
+ draw()
}
class RealImage {
+ draw()
}

ListUI ..> Image
Image <|.. ProxyImage
Image <|.. RealImage
RealImage <-- ProxyImage
@enduml